[
    {
      "id": 0,
      "name": "Kamruzzaman Chowdhury Tuhin",
      "position": "Chairman",
      "image": "/dignity/team/k1.jpg",
      "education": "",
    },
    {
      "id": 1,
      "name": "Shihab Chowdhury",
      "position": "Managing Director",
      "image": "/dignity/team/s2.jpg",
      "education": "Engineer, BSc(IUB), MBA(DU)",
    },
    {
      "id": 2,
      "name": "Sayeed Tanvir Alam",
      "position": "International Relationship Manager",
      "image": "/dignity/team/t1.jpg",
      "education": "Engineer, BSc",
    },
    {
      "id": 3,
      "name": "Muhammad Asif Hossain",
      "position": "Head, Information Technology",
      "image": "/dignity/team/a1.jpg",
      "education": "Engineer, BSc",
    },
    {
      "id": 4,
      "name": "Debashish Sarker",
      "position": "Head, Human Resource",
      "image": "/dignity/team/d1.jpg",
      "education": "Engineer, MSc",
    },
    {
      "id": 5,
      "name": "Sanjish Saha",
      "position": "Administrative Officer",
      "image": "/dignity/team/s1.jpg",
      "education": "Engineer, BSc",
    },
    {
      "id": 6,
      "name": "Soyab Mucktakim",
      "position": "Account Officer",
      "image": "/dignity/team/Shoyeb.jpg",
      "education": "Master’s In Accounting",
    },
    {
      "id": 7,
      "name": "Asif Istiaque",
      "position": "Senior Software Developer, IT",
      "image": "/dignity/team/a2.jpg",
      "education": "Engineer, MSc",
    },
    ]
